insert into alien values(123,'takshima','catwalk')
insert into alien values(124,'varun','salsa')
insert into alien values(129,'roshni','salsa')
insert into alien values(130,'purvi','salsa')
insert into alien values(131,'amelia','salsa')
insert into alien values(125,'ritika','bacha')
insert into alien values(126,'varsha','kutta')
